server:
  port: 8080
spring:
  application:
    name: gateway
  config:
    import: "configserver:"
  cloud:
    discovery:
      enabled: true
    config:
      discovery:
        enabled: true
        service-id: Config
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
        max-attempts: 6
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
          routes:
            - id: mcp-tools
              uri: lb://mcp
              predicates:
                - Path=/mcp/tools/**
              filters:
                - StripPrefix=2
              order: -1

  profiles:
    active: dev
  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: http://eureka-1:8761/eureka, http://eureka-2:8762/eureka
    register-with-eureka: false
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 0
    registry-fetch-interval-seconds: 5
management:
  endpoints:
    web:
      exposure:
        include: "*"
    access:
      default: unrestricted
  endpoint:
    gateway:
      access: unrestricted
