server:
  port: 8080
spring:
  application:
    name: Gateway
  config:
    import: "configserver:"
  cloud:
    discovery:
      enabled: true
    config:
      discovery:
        enabled: true
        service-id: Config
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
        max-attempts: 6
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://eureka-1:8761/eureka, http://eureka-2:8762/eureka
    register-with-eureka: true
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 0
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: gateway-${REPLICA_ID:1}
    hostname: gateway-${REPLICA_ID:1}
    appname: gateway