spring:
  profiles:
    active: ${SPRING_PROFILE:dev}
  application:
    name: gateway
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 4000
        multiplier: 1.1
        max-attempts: 10

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_REPLICAS:http://eureka-1:8761/eureka,http://eureka-2:8762/eureka,http://eureka-3:8763/eureka}
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}
    hostname: ${spring.application.name}
    app-group-name: ${spring.application.name}